#!/bin/bash
#   Eligius Monitoring/Notification
#   Instructions:
#       add siren.cfg with 
#           USERNAME (Eligius mining address)
#           CONTACTS (simple array of phone numbers [no dashes or spaces])
#           WAITTIME (optional, in seconds)
#       Run post-install.sh as root
#       Add to crontab: 0 8,10,12,14,16,18,20,22 * * * /bin/siren

#   Get Config Settings

source /etc/siren.cfg

#   Get Current Pool Balance (everpaid)

url="http://eligius.st/~wizkid057/newstats/api.php?cmd=getuserstat&username="
api="http://textbelt.com/text"
bal="/home/dajoker29/.balance.txt"
content="$(curl -s "$url$USERNAME")"

balance="$(echo $content | grep -Po '"everpaid":(\d*?,|.*?[^\\]",)' | awk -F ':' '{print $2}' | sed 's/,$//')"

if [ -a $bal ]; then
    oldbal=$(cat $bal)
    if [ "$balance" -ne "$oldbal" ]; then
        diff="$(expr $balance - $oldbal | awk '{printf( "%." C "f", $1 / 10^C) }' C=8)"

        for x in $CONTACTS; do
            curl $api -d number=$x -d "message=Eligius has recently paid out $diff BTC" > /dev/null 2>&1
        done

        echo $balance > $bal
    fi
else
    echo $balance > $bal
fi
